---
title: "R for Geospatial"
author: Caitlin C. Mothes, PhD (ccmothes@colostate.edu)
subtitle: "Geospatial Centroid @ CSU"
---

## Welcome

This is the **R for Geospatial** course website where you will find all necessary material. This course is designed for individuals with a basic understanding of R and RStudio and an interest in working with spatial data. **If you are new to R/RStudio, please review the [R Basics](basics.qmd) page before the workshop, including the attached lessons/tutorials**. Even if you have R experience, it is recommended to still review the introductory material to make sure everyone is on the same page by the start of the workshop.

In this workshop you will learn how to better handle, analyze, and visualize spatial data in R. You will also be exposed to various open-source spatial databases and learn how to access them directly from R to pull in data. The general breakdown of the workshop is as follows:**\
Lesson 1:**

-   Introduction to spatial data formats (vector and raster)
-   Importing, cleaning and manipulating spatial data

**Lesson 2:**

-   Spatial analysis (e.g., buffer, intersect, extract, spatial joins, distance and area calculations)
-   Basic plotting

**Lesson 3:**

-   Spatial data visualization (static, dynamic, interactive)
-   Data sharing (e.g., Shiny, R Markdown)

***Before Lesson 1 of the workshop you must go to the [Getting Started](setup.qmd) page to complete all pre-workshop steps and set-up your workspace with the necessary software and packages***. We will have set-up hours 30 minutes before the start of Lesson 1 if you need assistance, or you can email [ccmothes\@colostate.edu]{.underline} with any set-up issues.
